# A seção 'services' define os diferentes contêineres que compõem a sua aplicação.
services:
  # 'api' é o nome que damos ao nosso serviço/contêiner principal.
  api:
    build: . # 'build: .' instrui o Docker a construir a imagem a partir do Dockerfile no diretório atual.
    container_name: api # 'container_name' define um nome fixo e legível para o contêiner, facilitando sua identificação.
    ports:
      - "8000:8000" # 'ports' mapeia uma porta do seu computador (host) para uma porta do contêiner.
        # Mapeamos a porta 8000 do host para a 8000 do contêiner, onde a API está rodando.
    volumes:
      - .:/app
    # 'volumes' sincroniza uma pasta do seu computador com uma pasta dentro do contêiner.
    # '.:/app' sincroniza o diretório atual do projeto com o diretório /app no contêiner.
    # Isso permite o "live reload" e a persistência do banco de dados SQLite no seu computador.
    